### ISSUE TITLE
Site description

### ISSUE THREAD

**Issue by jazzi** [kishaningithub/hugo-shopping-product-catalogue-simple#2]
Added `description = "hi it's me"` to the bottom of config.toml, but didn't work, anything wrong?

**Comment by polarfish** [comment]
You can add description yourself like on the example below

![hugo-shopping-product-catalogue-simple-description-example](https://user-images.githubusercontent.com/1070579/42588227-dd899508-8545-11e8-84c6-0d82c21ed92d.png)

![hugo-shopping-product-catalogue-simple-description-example-browser](https://user-images.githubusercontent.com/1070579/42588241-e6298a60-8545-11e8-86f2-4ab901e89c96.png)

**Comment by kishaningithub** [comment]
@jazzi @polarfish Will add this feature to the theme
