### ISSUE TITLE
404 page not found

### ISSUE THREAD

**Issue by vallamost** [kishaningithub/hugo-shopping-product-catalogue-simple#3]
When I git cloned the theme, add the theme to my config and run

hugo server -D

visiting the localhost just shows a 404 for:

http://localhost:1313/products/

what I did:

hugo new site shop
cd shop
cd themes
git clone https://github.com/kishaningithub/hugo-shopping-product-catalogue-simple.git
rm -rf hugo-shopping-product-catalogue-simple/.git
cd ..
 echo 'theme = "hugo-shopping-product-catalogue-simple"' >> config.toml
hugo server -D

did I miss something?

**Comment by jazzi** [comment]
@isseiler Try copy all files within exampleSite into your document root (like /var/www/domain.com/)

**Comment by vallamost** [comment]
@jazzi Can you clarify? I'm a bit new to hugo. 

exampleSite only includes:

config.toml, content (dir), static (dir), there's no default document, etc.

**Comment by jazzi** [comment]
@isseiler yes, copy all files in exampleSite into your hugo site

**Comment by vallamost** [comment]
Oh figured it out. The config in the exampleSite was referencing hugo-shopping-product-catalogue-simple but I had left it named hugo-shopping-product-catalogue-simple-master
