### ISSUE TITLE
"ALL" category navigates for parent folder of site. 

### ISSUE THREAD

**Issue by ConorIA** [kishaningithub/hugo-shopping-product-catalogue-simple#6]
Hi, I have a *very* rough start here: https://conoria.gitlab.io/nugnu/categories/cakes/

I noticed that if I click on the "ALL" category, I get bumped back to https://conoria.gitlab.io/products, instead of https://conoria.gitlab.io/nugnu/products. I'm not sure if the issue is in my config, or in the theme. 

`baseURL = "https://conoria.gitlab.io/nugnu/"` in my toml

**Comment by kishaningithub** [comment]
As you said it should have gotten redirected to `https://conoria.gitlab.io/nugnu/products/` on clicking the "ALL" category. Will fix it.

**Comment by kishaningithub** [comment]
@ConorIA Have fixed the issue. Can you check now ?
Thanks a lot for reporting ☺️
